### ISSUE TITLE
Chore: Separate domain for short links?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/linky#14]
As noted in dwyl/app#284, an integral part of our App will be link management, shortening and tracking.
For that we are considering registering a _separate_ domain name that is even shorter than the `6 characters` we have in `dwyl.co` ... this will require a few hours of research ... ⌛ 
Opening this issue to keep track of the search.

**Comment by nelsonic** [comment]
Having second thoughts about the **`dwy.is`** domain ... 😕 
Really wish I had someone to "bounce ideas" with ... 💡 💬 
Like a co-founder/partner that wanted to build a software product more than _anything_ [`else`](https://github.com/dwyl/home/issues/29#issuecomment-1159571497). 👩‍💻 

The **`.is`** top level domain is associated with **`Iceland`** 🇮🇸 https://en.wikipedia.org/wiki/.is

![image](https://user-images.githubusercontent.com/194400/187598482-3440a91d-4050-455f-8c1d-2d6aff55afad.png)

Nothing wrong with that. But "dwyis" doesn't really _mean_ anything. 🤷‍♂️ 
We could try and come up with a https://en.wikipedia.org/wiki/Backronym for it ... 💭 

Need to get back to _building_ things. ⏳ 
Going to stop _thinking_ about this and **do it**. ✅
It's **`€38`** for the **`option`** of using it. 💸 💧 🪣 

![image](https://user-images.githubusercontent.com/194400/187603377-6943d7a3-fb95-48c1-8ce7-04144d608fa6.png)

Done. 🚀

**Comment by iteles** [comment]
I didn't see this until today because I'm still working through 'priority-1' labels.
