### ISSUE TITLE
We are confused about Mixins... What do they do?

### ISSUE THREAD

**Issue by naazy** [dwyl/linky#2]

**Comment by jrans** [comment]
@naazy Correct me if I'm wrong but I can't see one reference to a mixin in this whole repo?

**Comment by naazy** [comment]
@jrans True! but just thought we'd ask anyway ;)

**Comment by jrans** [comment]
Not the code in this repo is using es6 classes and react doesn't support them. If you still wish to go down the road first understand what a mixin is [here](https://facebook.github.io/react/docs/reusable-components.html#mixins) and see this [module](https://github.com/brigand/react-mixin) for support.

**Comment by nelsonic** [comment]
We aren't using **`mixins`** anywhere. 
See: https://en.wikipedia.org/wiki/Mixin
