### ISSUE TITLE
We are confused about Jsdom. It's in the package.json but we're not sure what it's doing

### ISSUE THREAD

**Issue by naazy** [dwyl/linky#4]
does it help with API requests?

**Comment by jrans** [comment]
JSDom is used in the integration tests namely this [file](https://github.com/dwyl/setup/blob/master/test/front/integration/init_fake_dom.js). We create a fake dom to render into and then can perform checks like document.getElementById etc... [React-Test-Utils](https://facebook.github.io/react/docs/test-utils.html) would also be useful here.
